service: silver-validate-bronze-inputs

frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  stage: dev
  architecture: x86_64
  timeout: 60
  memorySize: 256
  environment:
    DATA_LAKE_BUCKET: ftn-social-data-pipeline-2026
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::ftn-social-data-pipeline-2026/bronze/hackernews/*
            - arn:aws:s3:::ftn-social-data-pipeline-2026/bronze/x/*
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::ftn-social-data-pipeline-2026
  vpc:
    securityGroupIds:
      - "Fn::ImportValue": "infra-vpc-dev-LambdaSecurityGroupId"
    subnetIds:
      - "Fn::ImportValue": "infra-vpc-dev-PrivateSubnetA"
      - "Fn::ImportValue": "infra-vpc-dev-PrivateSubnetB"

package:
  individually: true
  patterns:
    - '!**'
    - 'src/**'

functions:
  validateBronzeInputs:
    name: silver-validate-bronze-inputs
    handler: src.handler.lambda_handler

resources:
  Resources:
    ValidateBronzeInputsErrorsAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: silver-validate-bronze-inputs-errors
        AlarmDescription: Sends Discord notification whenever the validation Lambda execution fails.

        Namespace: AWS/Lambda
        MetricName: Errors

        Dimensions:
          - Name: FunctionName
            Value: silver-validate-bronze-inputs

        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 0

        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: notBreaching

        AlarmActions:
          - ${cf:lambda-discord-notifier-dev.PipelineFailuresTopicArn}